name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/trezor/blockbook.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Rebase onto Upstream
        run: |
          git rebase upstream/master
          git push origin main --force
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
